---
name: Auto Increment Version Tag
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Get the latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null \
            || echo "v0.1.1")
          echo "Latest tag: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_OUTPUT
      - name: Calculate new version
        id: new_tag
        run: |
          latest_tag=${{ steps.get_tag.outputs.LATEST_TAG }}
          version=${latest_tag#v}
          IFS='.' read -r -a parts <<< "$version"
          major="${parts[0]}"
          minor="${parts[1]}"
          patch="${parts[2]}"
          new_patch=$((patch + 1))
          new_version="v$major.$minor.$new_patch"
          echo "New version: $new_version"
          echo "NEW_TAG=$new_version" >> $GITHUB_OUTPUT
      - name: Create new tag
        run: |-
          new_tag=${{ steps.new_tag.outputs.NEW_TAG }}
          echo "Creating new tag: $new_tag"
          git tag "$new_tag"
          git push origin "$new_tag"
