---
name: Run pre-commit
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
